#!/bin/bash
# reads all scalers in a condor job

if [ $# -ne 1 ]; then
  echo "Usage: $0 [board]"
  exit
else
  bd=$1
fi

f="reader.bat"
outdir="datfiles_bd$bd"
indir="sca2011t/bd$bd"

echo "Executable = sca_read_bin.o" > $f
echo "Universe = vanilla" >> $f
echo "notification = never" >> $f
echo "getenv = True" >> $f
echo "+Experiment = \"star\"" >> $f
echo "+Job_Type = \"cas\"" >> $f
echo  >> $f

mkdir -p log
rm log/*
for file in $(ls $indir); do
  echo "Arguments = $indir/$file" >> $f
  runnum=$(echo $file | cut -c4-11)
  logname=$(echo $file | sed 's/\.sca//g')
  echo "Log = log/${logname}.log" >> $f
  echo "Output = log/${logname}.out" >> $f
  echo "Error = log/${logname}.err" >> $f
  echo "Queue" >> $f
  echo >> $f
done

condor_submit $f
